# This is a basic workflow to help you get started with Actions

name: Lint

# Controls when the workflow will run
on:
  push:
    branches: [ "main", "develop" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3.3.0
      - name: Install modules
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: check build
        run: npm run build
