name: Release

on:
  push:
    tags:
      - "*.*.*"

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    - uses: actions/setup-node@v3.3.0
    - name: Install modules
      run: npm ci
    - name: build
      run: npm run build
    steps:
      - uses: actions/checkout@v3
      - id: packExtensionDir
        uses: cardinalby/webext-buildtools-pack-extension-dir-action@v1
        with:
          extensionDir: "./dist"
          zipFilePath: "build/qkd.zip"

      - uses: cardinalby/webext-buildtools-chrome-crx-action@v2
        with:
          zipFilePath: "build/qkd.zip"
          crxFilePath: "build/qkd.crx"
          privateKey: ${{ secrets.CHROME_EXTENSION_DEPLOY_KEY }},

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: build/qkd.crx
